==== ADS 7843 Serial Driver

*Syntax:*
[subs="quotes"]
----
    ADS7843_Init

    ADS7843_GetXY

    ADS7843_SetPrecision

----
*Command Availability:*

Available on all microcontrollers. Requires the inclusion of the following:

----
    #include <ADS7843.h>
----

*Explanation:*

The ADS7843 device is a 12-bit sampling Analog-to-Digital Converter (ADC) with a synchronous serial interface and low on resistance switches for driving touch screens.

The GCBASIC driver is integrated with the SDD1289 GLCD driver.  To use the ADS7843 driver the following is required to added to the GCBASIC source file.



`ADS7843_Init` is required to initialise the touch screen. This is mandated.

`ADS7843_GetXY` this sub-routine returns the X and Y coordinates of touched point.

`ADS7843_SetPrecision` this sub-routine sets the level of precision of the touch screen.

*Required Constants:*


[cols=3, options="header,autowidth"]
|===

|*Constants*
|*Controls/Direction*
|*Default Value*

|ADS7843_DOUT (IN)
|The chip output pin
|Mandated

|ADS7843_IRQ (IN)
|The interrupt pin
|Mandated

|ADS7843_CS (OUT)
|The chip select pin
|Mandated

|ADS7843_CLK (OUT)
|The clock pin
|Mandated

|ADS7843_DIN (OUT)
|The chip input pin
|Mandated

|===

The GCBASIC commands supported for this chip are:

[cols=3, options="header,autowidth"]
|===

|*Command*
|*Purpose*
|*Example*

|ADS7843_Init
|Initialise the device.
|ADS7843_Init [Optional precision = PREC_EXTREME]

|ADS7843_GetXY
|Returns the X and Y coordinates of touched point.
|ADS7843_GetXY (TP_X, TP_Y )

|ADS7843_SetPrecision
|Set the precision of the conversion result.
|ADS7843_SetPrecision(precision) +
(with PREC_EXTREME the conversion error is less than 3%)

|===


Precision can be set to four values as shown in the table below.
Passing a parameter of ADS7843_SetPrecision changes the precision controls.

[cols=3, options="header,autowidth"]
|===

|*Constants*
|*Defined  Value*
|*Default Value*

|`#define PREC_LOW`
|`1`
|

|`#define PREC_MEDIUM`
|`2`
|

|`#define PREC_HI`
|`3`
|

|`#define  PREC_EXTREME`
|`4`
|Default Value


|===



*Example:*

For more information see http://www.ti.com/product/ads7843.

This example shows how to drive a SDD1289 based Graphic LCD module with ADS7843 touch controller.

----

include::ADS7843SerialDriver_code1.gcb[]

----
