// erv updated demo code to table
==== Alloc


*About Alloc*

Alloc creates a special type of variable - an array variant. &#160;&#160;This array variant can store values.&#160;&#160;  The values stored in this array variant must be of the same type.

Essentially, ALLOCate will reserve a memory range as described by the given layout that can be used as a RAM buffer or as an array variant.


Layout:
----
  Dim variable_name as ALLOC * memory_size at memory_location
----

The allocated block of memory will not be initialized.



Example Usage:

----
  Dim my256bytebuffer as alloc * 256 at 0x2400
----

There is a pointer to allocated memory.  Use @variable_name.

Example Pointer
----
    HSerPrint @my256bytebuffer
----

*Extents*

This method can be unsafe because undefined behaviour can result if the caller does not ensure that buffer extents are not maintained. &#160;&#160; Buffer extents are 0 (zero) to the memory_size - 1

Example Extents:

----
    my256bytebuffer(0)    = some_variable.  Will address location 0x2400
    my256bytebuffer(255)  = some_variable.  Will address location 0x24FF ' the 256th byte of the allocated memory
----

Implementers of ALLOC must ensure memory constraints remain true.

*Safety*

This method is unsafe because undefined behaviour can result if the caller does not ensure that buffer extents are not maintained. &#160;&#160;   If buffer extents are exceeded the program may address areas of memory that have adverse impact on the operation of the microcontroller.

Examples of unsafe usage:
----
    my256bytebuffer(256) = some_variable.  Will address location 0x2500  ' this is the first byte of BUFFER RAM on the 18FxxQ43 chips... bad things may happen
    my256bytebuffer(65535) = some_variable.  Will address location 0x123FF  ' this is the beyond the memory limit and the operation will write an SFR.
----

*Example Program*

The following example program shows the ALLOCation of a 256 byte buffer at a specific address.&#160;&#160;
The array variant is then populated with data and then shown on a serial terminal.

----
include::alloc_code1.gcb[]

----

*For more help, see* <<_dim,Declaring arrays with DIM>>
