// Edit EvanV 171016
==== Analog/Digital Conversion Code Optimisation

(((Analog/Digital conversion,Analog/Digital Conversion Code Optimisation)))


*About Analog/Digital Conversion Code Optimisation*

The analog-to-digital converter (ADC or A/D) module support is implemented by GCBASIC to provide 8-bit, 10-bit, and 12-bit single-channel measurement mode and differential-channel measurement mode, with support for up to 34 channels. For compatibility, all channels are supported by default.

There are two methods to optimise the code:

1. Minimise the code by using constants to disable support for specific channels.
2. Adapt the ADC configuration by inserting specific commands to set registers or register bits.

*1. Minimise the Code*

The example below disables support for ADC port 0 (AD0).

[source,gcbasic]
----
    #define USE_AD0 FALSE
----

The following tables show the `#define` constants that can be used to reduce code size -- these are the defines for the standard microcontrollers. For 16F1688x and similar microcontrollers, see the second table.

[cols=3, options="header,autowidth"]

|===

|Channel
|Optimisation Value
|Default Value

|`USE_AD0`
|`FALSE`
|`TRUE`

|`USE_AD1`
|`FALSE`
|`TRUE`

|`USE_AD2`
|`FALSE`
|`TRUE`

|`USE_AD3`
|`FALSE`
|`TRUE`

|`USE_AD4`
|`FALSE`
|`TRUE`

|`USE_AD5`
|`FALSE`
|`TRUE`

|`USE_AD6`
|`FALSE`
|`TRUE`

|`USE_AD7`
|`FALSE`
|`TRUE`

|`USE_AD8`
|`FALSE`
|`TRUE`

|`USE_AD9`
|`FALSE`
|`TRUE`

|`USE_AD10`
|`FALSE`
|`TRUE`

|`USE_AD11`
|`FALSE`
|`TRUE`

|`USE_AD12`
|`FALSE`
|`TRUE`

|`USE_AD13`
|`FALSE`
|`TRUE`

|`USE_AD14`
|`FALSE`
|`TRUE`

|`USE_AD15`
|`FALSE`
|`TRUE`

|`USE_AD16`
|`FALSE`
|`TRUE`

|`USE_AD17`
|`FALSE`
|`TRUE`

|`USE_AD18`
|`FALSE`
|`TRUE`

|`USE_AD19`
|`FALSE`
|`TRUE`

|`USE_AD20`
|`FALSE`
|`TRUE`

|`USE_AD21`
|`FALSE`
|`TRUE`

|`USE_AD22`
|`FALSE`
|`TRUE`

|`USE_AD23`
|`FALSE`
|`TRUE`

|`USE_AD24`
|`FALSE`
|`TRUE`

|`USE_AD25`
|`FALSE`
|`TRUE`

|`USE_AD26`
|`FALSE`
|`TRUE`

|`USE_AD27`
|`FALSE`
|`TRUE`

|`USE_AD28`
|`FALSE`
|`TRUE`

|`USE_AD29`
|`FALSE`
|`TRUE`

|`USE_AD30`
|`FALSE`
|`TRUE`

|`USE_AD31`
|`FALSE`
|`TRUE`

|`USE_AD32`
|`FALSE`
|`TRUE`

|`USE_AD33`
|`FALSE`
|`TRUE`

|`USE_AD34`
|`FALSE`
|`TRUE`

|===

For 16F1688x devices, see the table below.

[cols=3, options="header,autowidth"]

|===

|Channel
|Optimisation Value
|Default Value


|`USE_ADA0`
|`FALSE`
|`TRUE`

|`USE_ADA1`
|`FALSE`
|`TRUE`

|`USE_ADA2`
|`FALSE`
|`TRUE`

|`USE_ADA3`
|`FALSE`
|`TRUE`

|`USE_ADA4`
|`FALSE`
|`TRUE`

|`USE_ADA5`
|`FALSE`
|`TRUE`

|`USE_ADA6`
|`FALSE`
|`TRUE`

|`USE_ADA7`
|`FALSE`
|`TRUE`


|`USE_ADC0`
|`FALSE`
|`TRUE`

|`USE_ADC1`
|`FALSE`
|`TRUE`

|`USE_ADC2`
|`FALSE`
|`TRUE`

|`USE_ADC3`
|`FALSE`
|`TRUE`

|`USE_ADC4`
|`FALSE`
|`TRUE`

|`USE_ADC5`
|`FALSE`
|`TRUE`

|`USE_ADC6`
|`FALSE`
|`TRUE`

|`USE_ADC7`
|`FALSE`
|`TRUE`


|`USE_ADD0`
|`FALSE`
|`TRUE`

|`USE_ADD1`
|`FALSE`
|`TRUE`

|`USE_ADD2`
|`FALSE`
|`TRUE`

|`USE_ADD3`
|`FALSE`
|`TRUE`

|`USE_ADD4`
|`FALSE`
|`TRUE`

|`USE_ADD5`
|`FALSE`
|`TRUE`

|`USE_ADD6`
|`FALSE`
|`TRUE`

|`USE_ADD7`
|`FALSE`
|`TRUE`


|`USE_ADE0`
|`FALSE`
|`TRUE`

|`USE_ADE1`
|`FALSE`
|`TRUE`

|`USE_ADE2`
|`FALSE`
|`TRUE`

|===

The following is an example that disables every channel except the specified channel, by defining every channel except `USE_AD0` as `FALSE`.

This saves 146 bytes of program memory.

[source,gcbasic]
----
include::analogdigitialconversionoptimisation_code1.gcb[]
----

For the 16F18855 family of microcontrollers, the following is an example. This saves 149 bytes of program memory.

[source,gcbasic]
----
include::analogdigitialconversionoptimisation_code2.gcb[]
----

*2. Adapt the ADC Configuration*

Example 1:

The following example sets specific register bits. The instruction is added to the compiled code.

[source,gcbasic]
----
    #define ADReadPreReadCommand  ADCON.2=0:ANSELA.0=1
----

The constant `ADReadPreReadCommand` can be used to adapt the ADC methods. The constant can enable registers or register bit(s) that need to be managed for a specific solution.

In the example above, the following assembly is added to your code. This is added just before the ADC is enabled and the acquisition delay is set.

[source,gcbasic]
----

  ;ADReadPreReadCommand
  banksel ADCON
  bcf ADCON,2
  banksel ANSELA
  bsf ANSELA,0

----

Example 2:

The following example can be used to change the ADMUX register to support a sensor on ADC4.

This supports reading the internal temperature sensor on the ATtiny85. This method also works on other similar chips -- refer to the chip-specific datasheet.

This calls a macro that changes the ADMUX register to read the ATtiny85 internal temperature sensor, sets the reference voltage to 1.1 V, and then waits 100 ms.

[source,gcbasic]
----

    #define ADREADPREREADCOMMAND ATTINY85ReadInternalTemperatureSensor

    Macro ATTINY85ReadInternalTemperatureSensor
    /*
    17.12 of the datasheet
    The temperature measurement is based on an on-chip temperature sensor that is coupled to a single ended ADC4
    channel. Selecting the ADC4 channel by writing the MUX[3:0] bits in ADMUX register to 1111 enables the temperature sensor. The internal 1.1V reference must also be selected for the ADC reference source in the
    temperature sensor measurement. When the temperature sensor is enabled, the ADC converter can be used in
    single conversion mode to measure the voltage over the temperature sensor.
    The measured voltage has a linear relationship to the temperature as described in Table 17-2 The sensitivity is
    approximately 1 LSB / ?C and the accuracy depends on the method of user calibration. Typically, the measurement
    accuracy after a single temperature calibration is +/-10?C, assuming calibration at room temperature. Better
    accuracies are achieved by using two temperature points for calibration.
    */
      IF ADReadPort=4 then
          ADMUX = ( ADMUX and 0X20 ) or 0X8F          ' <<< the register rewrite this page documents
          wait 100 ms
      End if

    End Macro


----
*Key line:* `ADMUX = ( ADMUX and 0X20 ) or 0X8F` -- masks out the existing channel-select bits while preserving the rest of ADMUX, then ORs in the ADC4-plus-1.1V-reference pattern this note describes.

This generates the following assembly.

[source,gcbasic]
----

    ;ADREADPREREADCOMMAND  'adds user code below
      lds SysCalcTempA,ADREADPORT
      cpi SysCalcTempA,4
      brne  ENDIF2
      ldi SysTemp2,32
      in  SysTemp3,ADMUX
      and SysTemp3,SysTemp2
      mov SysTemp1,SysTemp3
      ldi SysTemp2,143
      or  SysTemp1,SysTemp2
      out ADMUX,SysTemp1
      ldi SysWaitTempMS,100
      ldi SysWaitTempMS_H,0
      rcall Delay_MS
    ENDIF2:

----

**See Also:**

* <<_analog_digital_conversion_overview,Analog/Digital Conversion Overview>> -- category overview
* <<_adformat_deprecated_do_not_use,ADFormat (Deprecated - Do not use)>> -- related command in the same category
* <<_adoff,ADOff>> -- related command in the same category
