==== ByteToString

*Syntax:*
[subs="quotes"]
----
    _stringvar_ = ByteToString(_byte_variable_)     'supports byte.
----
*Command Availability:*

Available on all microcontrollers

*Explanation:*

The `ByteToString` function will convert a number into a string. `_number_` can be any byte variable, or a fixed number constant between 0 and 255 inclusive.&#160;&#160;For Word number use `WordToString()`, Long numbers use `LongToString()`, for Integer numbers use `IntegerToString()` and for Single numbers use `SingleToString()`

The string variable `_stringvar_` will contain the same number, represented as a string.&#160;&#160;The length of the string returned is 5 characters.

This function is especially useful if a number needs to added to the end of a string, or if a custom data sending routine has been created but only supports the output of string variables.
{empty} +
{empty} +
These methods will not support  conversion of hexadecimal number strings.
{empty} +
{empty} +
*Example1:*
----
    'Set chip model
    #chip 16F1936

    'Set up hardware serial connection
    #define USART_BAUD_RATE 9600
    #define USART_TX_BLOCKING

    Dim SensorReading as Byte

    'Take an A/D reading
    SensorReading = ReadAD(AN0)

    'Create a string variable
    Dim OutVar As String

    'Fill string with sensor reading
    OutVar = ByteToString(SensorReading)

    'Send
    HSerPrint OutVar
    HSerPrintCRLF

    When using the functions ByteToString() do not leave space between the function
    call and the left brace. You will get a compiler error that is
    meaningless.

    ' use this, note this is no space between the ByteToString() and the left brace!
    ByteToString(number_variable)
    ' do not use, note the space!
    ByteToString (number_variable)
----
{empty} +
{empty} +
*Example2:*
----
    '''
    '''
    '''
    '''
    '''************************************************************************
    '''
    '''  PIC: 16F18855
    '''  Compiler: GCB
    '''  IDE: GCode
    '''
    '''  Board: Xpress Evaluation Board
    '''  Date: June 2021
    '''
    ' ----- Configuration
      'Chip Settings.
      #chip 16f18855,32
      #Config CLRE_ON
      #option Explicit

    ; ----- Define Hardware settings

      'Set the PPS of the RS232 ports.
      UNLOCKPPS
        RC0PPS = 0x0010     'RC0->EUSART:TX;
        RXPPS  = 0x0011     'RC1->EUSART:RX;
      LOCKPPS

    ; ----- Constants
      #define USART_BAUD_RATE 19200
      #define USART_TX_BLOCKING

    ; ----- Variables
    dim bytevar as Byte

    ; ----- Main body of program commences here.
    bytevar = 0xff

    do
       wait 100 ms

       HSerPrint ByteToString( bytevar )
       HSerPrintCRLF
       wait 1 s
    loop
    end

; ----- Support methods.  Subroutines and Functions

----


{empty} +
{empty} +
*See Also* <<_wordtohex,WordToString>>, <<_longtohex,LongToString>>, <<_integertohex,IntegerToString>>, <<_singletohex,SingleToString>>, <<_bytetohex,ByteToHex>>
