=== Development Guide for GCBASIC.EXE compiler

There are lots of ways to contribute to the GCBASIC project: coding, testing, improving the build process and tools, or contributing to the documentation.
This guide provides information that will not only help you get started as a GCBASIC contributor, but that you will inform you as an experienced contributor wanting to help.

{empty} +

*Need Help?*

The GCBASIC community prides itself on being an open, accessible, and friendly community for new participants.&#160;&#160;
If you have difficulties getting involved or finding answers to your questions, please bring those questions to the forum via the discussion boards, where we can help you get started.

We know EVEN before you start contributing that getting can be a challenge.&#160;&#160;
This guide is intended to help.&#160;&#160;
We are always looking for ways to improve the software: making GCBASIC more open, accessible, and easier to participate with.&#160;&#160;
If you are having any trouble following this guide, or hit a barrier you cannot get around, please contact us via the discussion forum.&#160;&#160;
We will solve hurdles for new contributors and make GCBASIC better.&#160;&#160;

This addresses the changes and updates to the GCBASIC compiler.&#160;&#160;

{empty} +
{empty} +

*BACKGROUND*

The compiler was created by Dr. Hugh Considine when he was 12 years old.&#160;&#160;That was in 2005.&#160;&#160;Hugh came up with the idea for a new compiler - of the then available compilers - they were hard to use and not free. &#160;&#160;And, he had some spare time.

Hugh believes that GCBASIC should be free to all - forever.&#160;&#160;


The original software was called GCBASIC, but, he had some resistance in getting high schools in Australia to use and agree to the use of text based programming.&#160;&#160;
Graphical GCBASIC was created to address the need for a graphical user interface.&#160;&#160;Graphical GCBASIC acts like a set of training wheels. &#160;&#160;
The concept of Graphical GCBASIC is that the icons make it less scary, and since they all share names with the BASIC commands it is then easy to remember what command corresponds to each icon..&#160;&#160;
Using Graphical GCBASIC users can then switch to text mode whenever they want to, go backwards and forwards a few times if they want, and finally end up using just the text programming.&#160;&#160;
It is a journey from a graphical user interface to text based programming.&#160;&#160;
{empty} +
{empty} +
Those who already have programming experience can go straight to GCBASIC, while those who would prefer a lighter learning curve can take the Graphical GCBASIC option. &#160;&#160;
The two approaches targets two different sets of users who ultimately want to do the same thing.
{empty} +
{empty} +
As for the *name*, it was about the fourth name Hugh tried. &#160;&#160;First name was BASPIC, but it did not seem memorable enough.&#160;&#160;
Then, he considered some animal names - first thought was Chipmunk BASIC, but someone already used that!&#160;&#160;
Then, Bear BASIC, but decided against it on finding out the slang meaning of bear.&#160;&#160;
Final  name was GCBASIC, which is named after something his sister and he came up with (when aged 12 and 15!!).&#160;&#160;
No-one else had that name, it had no meanings that could offend, and it was something odd enough to be memorable, so GCBASIC it was.

In 2013 Evan Venn joined the team as a compiler developer, with others joining in Bernd Dau, Trevor Roydhouse, Pete Everett, Theo Loermans, Giuseppe D'Elia, Derek Gore,  Ian Smith, Bernd Dau, Theo Loermans, Urs Hopp, Kent Schafer, and Frank Steinberg.&#160;&#160;
Some those that joined in drove changes to the compiler, some changed the source code, some built tools and some built libraries.&#160;&#160;
They all had one thing in common - improvements to the GCBASIC compiler.

In 2021 we are still having new developers join the project like ToniG adding a new capability for handling Tables.

{empty} +
{empty} +

*THE COMPILER*

The compiler executable is called GCBASIC.EXE. &#160;&#160;
The compiler source is written in FreeBASIC.&#160;&#160;
FreeBASIC is a multiplatform, free/open source (GPL) BASIC programming language and a compiler for Microsoft Windows, protected-mode MS-DOS (DOS extender), Linux and FreeBSD.
&#160;&#160;
{empty} +
{empty} +
The official website is https://www.freebasic.net/[https://www.freebasic.net/]
{empty} +
{empty} +
FreeBASIC provides syntax compatibility with programs originally written in Microsoft QuickBASIC (QB).&#160;&#160;
FreeBASIC is a command line only compiler, unless users manually install an external integrated development environment (IDE) of their choice.&#160;&#160;
IDEs specifically made for FreeBASIC include FBide and FbEdit, while more graphical options include WinFBE Suite and VisualFBEditor.&#160;&#160;
{empty} +
{empty} +
The source code is Open Source.&#160;&#160;
And, has a GNU GENERAL PUBLIC LICENSE.&#160;&#160;
{empty} +
{empty} +
The source code for the compiler can be found on https://sourceforge.net/p/gcbasic/code/HEAD/tree/GCBASIC/trunk/[SourceForge]
{empty} +
{empty} +
Use SVN to UPDATE and COMMIT code changes.&#160;&#160;
You require developer access to SourceForge but if you have got this far then you already know this.&#160;&#160;
You are therefore  required to use SVN for source code management.

When COMMITting you MUST update the change log, then, when you commit an update use the change log with the SourceForge commit number.&#160;&#160;
Then, add the new change at the end of the change log.&#160;&#160;
The COMMIT message should be the same as the description in the change log.&#160;&#160;
Add the [_COMMIT NUMBER]_ to the description in the change log to show the COMMIT number.&#160;&#160;


You will find the changelog https://onedrive.live.com/Edit.aspx?resid=2F87FFE77F3DBEC7!67634&wd=cpe&authkey=!ADmkT3exl5l4Pkc[here].&#160;&#160;
The change log is an EXCEL spreadsheet.&#160;&#160;

{empty} +
{empty} +

*COMPILER ARCHITECTURE*

The compiler is relatively simple in terms of the architecture.&#160;&#160;
There is a main source program with a set of header files that contain other methods or declarations.&#160;&#160;
The GCBASIC header files are the following:

----
    1. preprocessor.bi -  methods, statements, defines, declarations, prototypes, constants, enumerations, or similar types of statements
    2. utils.bi - methods that are shared across the architecture
    3. variables.bi - methods that control the creation and management of variables
    4. assembly.bi - methods specific to the generation of GCAssembler (GCASM)
    5. file.bi - the FreeBASIC files library
    6. string.bi - the FreeBASIC string library
----
The supporting files are:

----
    1. messages.dat - the English messages source file.  All user messages from the compiler are sourced from this file.
    2. reservedwords.dat - the list of system reserved words
----
{empty} +
{empty} +
The compiler process is simple.&#160;&#160;
The process, shown below, generates the ASM source and the HEX file from the user source program.

----
    1. Create the indexes
    2. Declare the methods, arrays and variables
    3. Process the user source programs using PreProcessor method. This includes
        i.     Loading of all source files including including files
        ii.    Translate files, if needed
        iii.   Examine source for comments, tables, asm, rawasm, functions;subs;macros, set origin of valid code
                    Origin = ";?F" + Str(RF) + "L" + Str(LC) + "S" + Str(SBC) + "?"
                    RF = File number 
                    L  = Line number in source file
                    S  = Sub Routine number
        iv.    Find compiler directives, except SCRIPT, ENDSCRIPT, IFDEF and ENDIF - including all the #DEINEs outside of condiontal statements
        v.     ReadChipData
        vi.    CheckClockSpeed
        viii.  ReadOptions
        ix.    PreparePageData
        x.     PrepareBuiltIn.  Initialise built-in data, and prepare built-in subs.
        xi.    RunScripts
        xii.   BuildMemoryMap
        xiii.  Process samevar and samebit
        xiv.   RemIfDefs.  Remove any #IFDEFs that do not apply to the program. 
        xv.    Prepare programmer, need to know chip model and need to do this before checking config
        xvi.   Replace Constants
        xvii.  Replace table value.  Replace constants and calculations in tables with actual values
    4. Compile the program using the CompileProgram method
         i.    Compile calls to other subroutines, insert macros
         ii.   Compile DIMs again, in case any come through from macros
         iii.  Compile FOR commands
         iv.   Process arrays
         v.    Add system variable(s) and bit(s)
         vi.   Compile Tables
         vii.  Compile Pot
         viii. Compile Do
         ix.   Compile Dir
         x.    Compile Wait
         xi.   Compile On Interrupt
         xii.  Compile Set(s)
         xiii. Compile Rotate
         xiv.  Compile Repeat
         xv.   Compile Select
         xvi.  Compile Return
         xvii. Compile If(s)
         xviii Compile Exit Sub
         xix.  Compile Goto(s)
    5. Allocate RAM using the AllocateRAM method
    6. Optimise the generated code using the TidyProgram method
    7. Combine and locate the subroutines and functions for the selected chip using the MergeSubroutines method
    8. Complete the final optimisation using the FinalOptimise method
    9. Write the assembly using the WriteAssembly method
    10. Assemble and generate the hex file using GCASM, MPASM, PICAS or some other define Assembler
    11. Optionally, pass programming operations to the programmer
    12. Write compilation report using the WriteCompilationReport method
    13. If needed, write the error and warning log using the WriteErrorLog method
    14. Exit, setting the ERRORLEVEL
----

Note #1:  Constants are can be created in many places and the order is critical when trying to understant the process.

Step 3.iv; Step 3.xi, 3.xiv and xvi. These are Find compiler directives; Runscripts, process IFDEFs and replace Constants values respectively.&#160;&#160;
This means constants that are not created by the Find compiler directives step are clearly not available in the RunScripts step, and the same applies to the process IFDEFs step.&#160;&#160;So, please consider the order of constant creation in terms of these steps.&#160;&#160;Always think about the precendence of constant creation.&#160;&#160;

Note #2:  When using IFDEFs Conditional statements you should #UNDEFINE all constants prior to #DEFINE.&#160;&#160;Whilst the will be cases where the constant does not exist, or where the Preprocessor can determine the outcome of the Conditional statements there will be cases, specifically nested IFDEFs Conditional statements, where you will be required to use #UNDEFINE to remove all warnings.

Note #3:  Good practice is NOT to create constants in a library where the user can overwrite the value of the same constant.&#160;&#160;You must determine if the user has created the constant and then create a default value if the user has not defined a value.&#160;&#160;  An example:

----
  IF NODEF(AD_DELAY) THEN
     'Acquisition time. Can be reduced in some circumstances - see PIC manual for details
     AD_DELAY = 2 10US
  END IF
----

This will create the constant AD_DELAY only when the user program does not define a value.
{empty} +

*FreeBASIC COMPILATION OF GCBASIC SOURCE CODE*

The compiler is relatively simple in terms of the compilation.&#160;&#160;

Use the following versions of the FreeBASIC compiler to compile the GCBASIC source code.

For Windows 32 bit
----
    FreeBASIC Compiler - Version 1.07.1 (2019-09-27), built for win32 (32bit)
    Copyright (C) 2004-2019 The FreeBASIC development team.
----

For Windows 64 bit
----
    FreeBASIC Compiler - Version 1.07.1 (2019-09-27), built for win64 (64bit)
    Copyright (C) 2004-2019 The FreeBASIC development team.
----

Using other version of Windows FREEBASIC compiler are NOT tested and may fail.&#160;&#160;
Use the specific versions shown above.

The compile use the following command lines.
Where "%ProgramFiles% is the root location of the FreeBASIC installation, and
$SF is the location of the source files and the destination of the compiled executable.

For Windows 32 bit
----
    "%ProgramFiles%\FreeBASIC\win32\fbc.exe"  $SF\gcbasic.bas   -exx -arch 586 -x $SF\gcbasic32.exe
----

For Windows 64 bit
----
    "%ProgramFiles%\FreeBASIC\win64\fbc.exe"  $SF\gcbasic.bas   -x $SF\gcbasic64.exe -ex

----

Linux, FreeBSD and Pi OS are also supported.&#160;&#160;
Please see http://gcbasic.sourceforge.net/help/[Online Help] and search for the specific operating system.&#160;&#160;

{empty} +
{empty} +

*FreeBASIC COMPILER TOOLCHAIN*

To simplify the establishment of  development enviroment download a complete installation from https://sourceforge.net/projects/gcbasic/files/Support%20Files/GreatCowBASICWindowsToolchain/FreeBASIC.zip/download[here].&#160;&#160;
This includes the correct version of FreeBASIC and the libraries - all ready for use.&#160;&#160;
Simply unzip the ZIP to a folder and the toolchain is ready for use.&#160;&#160;
For an IDE please see the information above.&#160;&#160;

{empty} +
{empty} +

*BUILDING THE GCBASIC EXECUTABLE USING THE FBEDIT IDE*

To build GCBASIC from the source files.&#160;&#160;
The list shows the installation of the FBEdit IDE.


Complete the following:

----
        1. Download and install FreeBASIC from  url shown above.
        2. Download and install fbedit from https://sourceforge.net/projects/fbedit/?source=dlp
        3. Download the GCBASIC source using SVN into a gcbasic source folder.
        4. Run fbedit (installed at step #2).  Load project  GCBASIC.fbp  from GBASIC source folder.
        5. Hit <f5> to compile.
----

{empty} +
{empty} +

*CODING STYLES*

Remember, Hugh was 12 when he started this project.&#160;&#160;
You must forgive him for being a genius, but, he did not implement many programming styles and conventions that are common place today.&#160;&#160;

There is a general lack of documentation.&#160;&#160;
We are adding documentation as we progress.&#160;&#160;
This can make the source frustrating initially but can find the code segments as they are clearly within method blocks.&#160;&#160;

The following rules are recommended.

----
    1. All CONSTANTS are capitalized
    2. Do not use TAB - use two spaces
    3. You can rename a variable to a meaningful name.  Hugh used a lot of single character variables many years ago.  This should be avoided in new code.
    4. Document as you progress.
    5. Ask for help.

----

{empty} +


*COMPILER SOURCE INSIGHTS*

_There are many very useful methods_, a lot of methods, look at existing code before adding any new method.&#160;&#160;
The compiler is mature from a functionality standpoint.&#160;&#160;
Just immature in terms of documentation.&#160;&#160;

*COMPILER DEBUGGING*


_To debug or isolate a specific issue_ use lots of messages using PRINT or HSERPRINT&#160;&#160;Both of these methods are easy to setup and use.

_Specific to #SCRIPT_ you can use WARNING messages to display results of calculations or assignments.

_Specific to CONDITIONAL Compilation_ use `conditionaldebugfile` (se above) to display conditional statement debug for the specified file. &#160;&#160; Options are any valid source file or nothing. &#160;&#160;
Nested conditions are evaluated sequentially, therefor the first, second, third etc etc.  &#160;&#160; 
The compiler does not at this point rationalised the hierarchy of nested conditions.&#160;&#160;  It simply finds a condition and then matches to an #ENDIF.&#160;&#160;
So, the compiler walks through the nested conditions as the outer nested, then the next nest, the next nest etc. etc.&#160;&#160;
This compiler is completing the following actions:&#160;&#160;

1. If the conditional is not valid.&#160;&#160;  Remove the code segment include the #IF and the #ENDIF
2. If the conditional is valid.&#160;&#160;  Remove the just the #IF and the #ENDIF

So, is this context the compiler walks the code many time (as these are lists not arrrays this is blindly fast) removing code segments.&#160;&#160;

The following program shows the impact of nested conditions..&#160;&#160;Each nest is evaluated until all conditions have been assessed..&#160;&#160;See the comment section of the listing to see the output from the debugging.


----
        #CHIP 18F16Q41
        #OPTION EXPLICIT

        ; -----  Add the following line to USE.ini ------------------
        ;
        ;        conditionaldebugfile = IFDEF_TEST.gcb
        ;
        ; -----------------------------------------------------------

        #IFDEF PIC
            #IFDEF ONEOF(CHIP_18F15Q41, CHIP_18F16Q41)
                #IF CHIPRAM = 2048  'TRUE
                    #IF CHIPWORDS = 32768 ' TRUE
                        #IFDEF VAR(NVMLOCK) 'TRUE
                            #IFDEF VAR(OSCCON2)  'TRUE
                                #IFDEF  VAR(NVMCON0)  'TRUE    set var1 to 1
                                    DIM _VAR1
                                    _VAR1 = 1
                                #ENDIF
                            #ENDIF
                        #ENDIF
                    #ENDIF
                #ENDIF

                #IF CHIPRAM = 4096  'TRUE
                    #IF CHIPWORDS = 32768 ' TRUE
                        #IFDEF VAR(NVMLOCK) 'TRUE
                            #IFDEF VAR(OSCCON2)  'TRUE
                                #IFDEF  VAR(NVMCON0)  'TRUE   = set var1 to 0
                                    DIM _VAR1
                                    _VAR1 = 0
                                #ENDIF
                            #ENDIF
                        #ENDIF
                    #ENDIF
                #ENDIF
            #ENDIF
        #ENDIF

        Do
        Loop

        // ===============================================
        // ***  Below is debugger output for this file ***
        // ===============================================

        // GCBASIC (0.99.02 2022-07-21 (Windows 32 bit) : Build 1143)

        // Compiling c:\Users\admin\Downloads\IFDEF_TEST.gcb

        //               13: #IFDEF PIC
        //               15: #IFDEF ONEOF(CHIP_18F15Q41, CHIP_18F16Q41)
        //               17: #IF CHIPRAM = 2048
        //               19: #IF CHIPWORDS = 32768
        //               21: #IFDEF VAR(NVMLOCK)
        //               23: #IFDEF VAR(OSCCON2)
        //               25: #IFDEF VAR(NVMCON0)
        //               ;DIM _VAR1
        //               27: DIM _VAR1
        //               ;_VAR1 = 1
        //               28: _VAR1 = 1

        //               15: #IFDEF ONEOF(CHIP_18F15Q41, CHIP_18F16Q41)
        //               17: #IF CHIPRAM = 2048
        //               19: #IF CHIPWORDS = 32768
        //               21: #IFDEF VAR(NVMLOCK)
        //               23: #IFDEF VAR(OSCCON2)
        //               25: #IFDEF VAR(NVMCON0)
        //               ;DIM _VAR1
        //               27: DIM _VAR1
        //               ;_VAR1 = 1
        //               28: _VAR1 = 1

        //               39: #IF CHIPRAM = 4096
        //               41: #IF CHIPWORDS = 32768
        //               43: #IFDEF VAR(NVMLOCK)
        //               45: #IFDEF VAR(OSCCON2)
        //               47: #IFDEF VAR(NVMCON0)
        //               ;DIM _VAR1
        //               49: DIM _VAR1
        //               ;_VAR1 = 0
        //               50: _VAR1 = 0

        //               41: #IF CHIPWORDS = 32768
        //               43: #IFDEF VAR(NVMLOCK)
        //               45: #IFDEF VAR(OSCCON2)
        //               47: #IFDEF VAR(NVMCON0)
        //               ;DIM _VAR1
        //               49: DIM _VAR1
        //               ;_VAR1 = 0
        //               50: _VAR1 = 0

        //               43: #IFDEF VAR(NVMLOCK)
        //               45: #IFDEF VAR(OSCCON2)
        //               47: #IFDEF VAR(NVMCON0)
        //               ;DIM _VAR1
        //               49: DIM _VAR1
        //               ;_VAR1 = 0
        //               50: _VAR1 = 0

        //               45: #IFDEF VAR(OSCCON2)
        //               47: #IFDEF VAR(NVMCON0)
        //               ;DIM _VAR1
        //               49: DIM _VAR1
        //               ;_VAR1 = 0
        //               50: _VAR1 = 0

        //               47: #IFDEF VAR(NVMCON0)
        //               ;DIM _VAR1
        //               49: DIM _VAR1
        //               ;_VAR1 = 0
        //               50: _VAR1 = 0

        // Program compiled successfully (Compile time: 1 seconds)

        // Assembling program using GCASM
        // Program assembled successfully (Assembly time: 0.125 seconds)
        // Done
----

{empty} +
{empty} +


The resulting ASM from the about code is as expected.&#160;&#160;The assignment of `VAR1 = 0`.&#160;&#160; 

----
        ;DIM _VAR1
        ;_VAR1 = 0
            clrf	_VAR1,ACCESS
        ;Do
        SysDoLoop_S1
        ;Loop
            bra	SysDoLoop_S1
        SysDoLoop_E1
----

{empty} +
{empty} +
{empty} +

=== Development Guide for GCBASIC Preferences Editor

This section deals with the GCBASIC Preferences Editor (Pref Editor).&#160;&#160;
The Prefs Editor is the software enables the user to select programmers, select the options when compiling, select the assembler and other settings.&#160;&#160;
The Prefs Editor uses an ini to read and store the compiler settings.&#160;&#160;
The INI structure is explained the first section, then, the Prefs Editor in detail.

{empty} +

*ABOUT THE INI FILES*

You can provide the compiler an INI file with a number of settings and programmers.&#160;&#160;

The following section provide details of the specifics within an example INI file.&#160;&#160;
The comments are NOT part of an INI file.&#160;&#160;

The settings are in the INI section called [gcbasic].&#160;&#160;


----
    [gcbasic]
    'The current order of the programmers as shown in Prefs Editor
    programmer = tinybootloader, lgt8fx8p, arduinouno, pickitpluscmd0, nsprog

    'Show the progress counters when compiling.  This can be changed in the INI or by a command line switch. There is no support in Prefs Editor to change this parameter.
    showprogresscounters = n

    'Show verbose when compiling.  This can be changed in the INI or by a command line switch
    verbose = n

    'Show source code in the generated ASM or .S files. This can be changed in the INI or by a command line switch
    preserve = a

    'Treat warning as errors. This can be changed in the INI or by a command line switch.&#160;&#160;There is no support in Prefs Editor to change this parameter.
    warningsaserrors = n

    'Pause after compilation. This can be changed in the INI or by a command line switch.&#160;&#160;There is no support in Prefs Editor to change this parameter.
    pauseaftercompile = n

    'Flash the chip only. This can be changed in the INI or by a command line switch. There is no support in Prefs Editor to change this parameter.
    flashonly = n

    'Selected assembler. This can be changed in the INI or by a command line switch.
    assembler = PIC-AS

    'Add comments to hex to show source compiler. This can be changed in the INI or by a command line switch.
    hexappendgcbmessage = n

    'Mute banners when compiling. This can be changed in the INI or by a command line switch. There is no support in Prefs Editor to change this parameter.
    mutebanners = n

    'Show the extended verbose messages when compiling. his can only be changed in the INI. There is no support in Prefs Editor or a command line switch to change this parameter.  Not managed by Prefs Editor.
    evbs = n

    'Use LAXSYNTAX supports lax validation.  This disables reserved word inspection, permits use of reserved words in GOTO statement.  Not managed by Prefs Editor.
    laxsyntax = y

    'Use NoSummary supports minimal compiler and assembly information when set to y.  Supports y|n.  Not managed by Prefs Editor.
    nosummary = n

    'Use the system temp directory for compiler temp files.  Options are "tempdir" or "instdir" or remove the option.
    workingdir = "tempdir"
    
    'Display conditional statement debug for the specified file.  Options are any valid source file or nothing. The enry will be remove if a prefixed by a comment ( a single quote ).
    conditionaldebugfile = 

----

The section shows an example [tool] assembler section.&#160;&#160;

----
    [tool=pic-as]
    'An assember
    type = assembler
    'Location of the assember using a parameter substitution.
    command = %picaslocation%\pic-as.exe
    'Parameters
    params = -mcpu=%ChipModel%  "%Fn_NoExt%.S" -msummary=-mem,+psect,-class,-hex,-file,-sha1,-sha256,-xml,-xmlfull  -Wl -mcallgraph=std -mno-download-hex -o"%Fn_NoExt%.hex"  -Wl,-Map="%Fn_NoExt%.map" -Wa,-a

    [tool=mpasm]
    'An assember
    type = assembler
    'Location of the assember using a parameter substitution.
    command = %mpasmlocation%\mpasmx.exe
    'Paramters
    params = /c- /o- /q+ /l+ /x- /w1 "%FileName%"

----



The section shows an example [patch] section.

This section shows and explicit set of patches applied to PIC-AS assembler.

----
    [patch=asm2picas]
    desc = PICAS correction entries.  Format is STRICT as follows:  Must have quotes and the equal sign as the delimeter. PartName +COLON+"BadConfig"="GoodConfig"    Where BadConfig is from .s file and GoodConfig is from .cfgmap file
    16f88x:"intoscio = "="FOSC=INTRC_NOCLKOUT"
    16f8x:"intrc = IO"="FOSC=INTOSCIO"
    12f67x:"intrc = OSC_NOCLKOUT"="FOSC=INTRCIO"
----

The section shows an example [programmer] section.&#160;&#160;

----
    [tool = pk4_pic_ipecmd_program_release_from_reset]
    'Description
    desc = MPLAB-IPE PK4 CLI for PIC 5v0
    'A programmer
    type = programmer
    'Command line using a parameter substitution.
    command = %mplabxipedirectory%\ipecmd.exe
    'Parameters using a parameter substitution.
    params = -TPPK4 -P%chipmodel%  -F"%filename%" -M  -E -OL -W5
    'Worting direcroty using a parameter substitution.
    workingdir = %mplabxipedirectory%
    'Useif constraints - this shows none
    useif =
    'Mandated programming config constraints - this shows none
    progconfig =
----


*ABOUT THE PREFS EDITOR*


This is a utility for editing GCBASIC ini files.&#160;&#160;
It is derived from the Graphical GCBASIC utilities, and requires some files from Graphical GCBASIC to compile.&#160;&#160;

The software is developed using Sharp Develop v.3.2.1 ( not Visual Studio ).&#160;&#160;


{empty} +

*COMPILING*

Ensure that the "Programmer Editor" folder is in the same folder as a "Graphical GCBASIC" folder.&#160;&#160;
The "Graphical GCBASIC" folder must contain the following files from GCGB:
 - Preferences.vb
 - PreferencesWindow.vb
 - ProgrammerEditor.vb
 - Translator.vb
 - ProgrammerEditor.resources

Once these files are in place, it should be possible to compile the Programmer Editor using SharpDevelop 3.2 (or similar).

{empty} +

*USING PREFS EDITOR*

If run without any parameters, this program will create an ini file in whatever directory it is located in.&#160;&#160;
If it is given the name of an ini file as a command line parameter, it will use that file.&#160;&#160;

As well as the ini file it is told to load, this program will also read any files that are included from that file..&#160;&#160;
This makes it possible to keep the settings file in the Application Data folder if GCBASIC is installed in the Program Files directory..&#160;&#160;
To put the settings file into the Application Data folder, create a small ini file containing the following 3 lines and place it in the same directory as this program:

----
    include %appdata%\gcgb.ini
    [gcgb]
    useappdata = true
----

The include line tells the program (and GCBASIC) to read from the Application Data folder.&#160;&#160;
The useappdata=true line in the [gcgb] section will cause this program to write any output to a file in Application Data called gcgb.ini.&#160;&#160;
The hard coding of GCGB is required this program is based on GCGB.&#160;&#160;
It will result in programmer definitions being shared between GCGB and any other environment using this editor, which may be a positive side effect.


{empty} +

*BUILDING THE PROGRAMMER EDITOR EXECUTABLE USING SHARP DEVELOP*

To build Prefs Editor from the source files.&#160;&#160;
The list shows the installation of the Sharp Develop IDE.


Complete the following:

----
        1. Download and install Sharp Develop from  https://sourceforge.net/projects/sharpdevelop/files/SharpDevelop%203.x/3.2/[SourceForge]
        2. Download the Prefs Editor source using SVN into a source folder.  This is the folder ..\utils\Programmer Editor
        4. Run Sharp Develop (installed at step #1).  Load project  "Programmer Editor.sln"  from source source folder.
        5. Hit <f8> to compile.
----


{empty} +
{empty} +
{empty} +
{empty} +
