==== GLCDPrintWithSize

(((Graphical LCD,GLCDPrintWithSize)))


*Syntax:*
[source,gcbasic]
----
    GLCDPrintWithSize(PrintLocX, PrintLocY, PrintData_Byte , FontSize [, Color ] )    ',or
    GLCDPrintWithSize(PrintLocX, PrintLocY, PrintData_Word , FontSize [, Color ] )    ',or
    GLCDPrintWithSize(PrintLocX, PrintLocY, PrintData_Long , FontSize [, Color ] )    ',or

    GLCDPrintWithSize(PrintLocX, PrintLocY, PrintData_String , FontSize [, Color ] )
----
{empty} +
{empty} +
`PrintLocX` is the X corrdinate location for the data +
`PrintLocY` is the Y coordinate location for the data +
`PrintData_[type]` is a variable or constant to be displayed +
`FontSize` is the GLCD fontsize.{nbsp}{nbsp} Typical values are 1, 2 or 3 +
`Color` is an optional parameter to change the color the GLCD printed text.
{empty} +
{empty} +
*Explanation:*
{empty} +
{empty} +
Prints data values (byte, word, long or string) at a specified location on the GLCD screen with a specific font size.
{empty} +
{empty} +
To display a string using font size two use:
{empty} +
{empty} +
[source,gcbasic]
----
    GLCDPrintWithSize(PrintLocX, PrintLocY, "Using font size #2", 2 )          ' <<< the GLCDPrintWithSize instruction
----
*Key line:* `GLCDPrintWithSize(PrintLocX, PrintLocY, "Using font size #2", 2 )` -- the fourth parameter (2) selects the font size, letting the same string be drawn larger or smaller than `GLCDPrint`'s single fixed size.
{empty} +
{empty} +

**See Also:**

* <<_glcd_overview,GLCD Overview>> -- category overview
* <<_glcdprint,GLCDPrint>> -- the fixed-size equivalent of this command
* <<_glcdprintlargefont,GLCDPrintLargeFont>> -- a dedicated large fixed font, string-only
