==== GLCDPrintLargeFont

(((Graphical LCD,GLCDPrintLargeFont)))


*Syntax:*
[source,gcbasic]
----
    GLCDPrintLargeFont( PrintLocX, PrintLocY, PrintData_String [, Optional Colour] )
----
GLCD supports for a larger fixed font of 13 pixels.{nbsp}{nbsp}  GLCDPrintLargeFont supports strings only.

{empty} +
{empty} +
`PrintLocX` is the X corrdinate location for the data +
`PrintLocY` is the Y coordinate location for the data +
`PrintData_[type]` is a variable or constant to be displayed
{empty} +
{empty} +
*Explanation:*
{empty} +
{empty} +
Prints data values (byte, word, long or string) at a specified location on the GLCD screen.
{empty} +
{empty} +
As an exmaple, to display an string use:
{empty} +
{empty} +
[source,gcbasic]
----
    GLCDPrintLargeFont( 0, 0, "13 Pixels Fixed Font" )          ' <<< the GLCDPrintLargeFont instruction
----
*Key line:* `GLCDPrintLargeFont( 0, 0, "13 Pixels Fixed Font" )` -- draws the string at pixel coordinates (0, 0) using the larger 13-pixel fixed font; unlike `GLCDPrint`, this command accepts strings only, not byte/word/long values.
{empty} +
{empty} +

**See Also:**

* <<_glcd_overview,GLCD Overview>> -- category overview
* <<_glcdprint,GLCDPrint>> -- the standard-font equivalent, which also accepts numeric values
* <<_glcdprintwithsize,GLCDPrintWithSize>> -- selecting a specific font size instead of the fixed large font
