//erv 04110218
==== HEFReadWord

(((HEFM ( PFM ),HEFReadWord)))



*Syntax:*
[subs="specialcharacters,quotes"]
----
    'as a subroutine
    HEFReadWord ( location, data_word_variable )

    'as a function
    data_word_variable = HEFReadWord ( location )
----
*Command Availability:*

Available on all PIC micro-controllers with HEFM memory

*Explanation:*
{empty} +
{empty} +
HEFReadWord is used to read information, word values, from HEFM so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` rerepresents the location or relative address to read.  The location will range from location 0 to HEF_BYTES - 1, or for all practical purposes 0-127 since all PIC Microcontrollers with HEF support 128 bytes of HEF Memory. HEF_BYTES is a GCBASIC constant that represents the number of bytes of HEF Memory.&#160;&#160;&#160;
{empty} +
{empty} +
`data` is the data that is to be read from the HEFM data storage.&#160;&#160;&#160;
This must be a word variable.&#160;&#160;&#160;
{empty} +
{empty} +
This method reads data from HEFM given the specific relative location.&#160;&#160;&#160;
{empty} +
{empty} +
*Example 1:*
[source,gcbasic]
----
    '... code preamble to select part
    '... code to setup serial

    'The following example reads the HEFM value into the word variable “data_word_variable” by initially writing some word values.

    dim data_word_variable as word
    HEFWriteWord( 254, 4660 )

    HEFReadWord( 254, data_word_variable )          ' <<< the HEFReadWord instruction (subroutine form)

    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF

----
{empty} +
If example 1 were displayed on a serial terminal.&#160;&#160;&#160;The result would show:

[source,gcbasic]
----
    Value = 4660
----
*Key line:* `HEFReadWord( 254, data_word_variable )` -- reads the word back from HEFM location 254 using the subroutine form, storing the result directly into `data_word_variable`.

{empty} +
{empty} +
*Example 2:*
[source,gcbasic]
----
    '... code preamble to select part
    '... code to setup serial

    'The following example uses a function to read the HEFM value into the word variable “data_word_variable”.

    dim data_word_variable as word
    HEFWriteWord( 254, 17185 )

    data_word_variable = HEFReadWord( 254 )          ' <<< the HEFReadWord instruction (function form)

    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF

----
{empty} +
If example 2 were displayed on a serial terminal.&#160;&#160;&#160;The result would show:

[source,gcbasic]
----
    Value = 17185
----
*Key line:* `data_word_variable = HEFReadWord( 254 )` -- reads the word back from HEFM location 254 using the function form, assigning the result to `data_word_variable`.

{empty} +
{empty} +
**See Also:**

* <<_hefm_overview,HEFM Overview>>
* <<_hefread,HEFRead>>
* <<_hefreadword,HEFReadWord>>
* <<_hefwrite,HEFWrite>>
* <<_hefwriteword,HEFWriteWord>>
* <<_hefreadblock,HEFReadBlock>>
* <<_hefwriteblock,HEFWriteBlock>>
* <<_heferaseblock,HEFEraseBlock>>
