==== HI2CStart

(((I2C/TWI Hardware Module,HI2CStart)))


*Syntax:*

[source,gcbasic]
----
    HI2CStart
----

*Command Availability:*

Only available for microcontrollers with the hardware I2C or TWI module.

*Explanation:*

If the HI2C routines are operating in Master mode, this command will
send a start condition. If routines are in Slave mode, it will pause the
program until a start condition is sent by the master. It should be
placed at the start of every I2C transmission.

*Note:*

This command is also available on microcontrollers with a second hardware I2C port.

[source,gcbasic]
----
    HI2C2Start
----

*Example:*
[source,gcbasic]
----
    'Writes a single byte to a hardware I2C EEPROM at device address 0xA0, memory address 0x00
    HI2CStart          ' <<< the HI2CStart instruction
    HI2CSend 0xA0
    HI2CSend 0x00
    HI2CSend 0x55
    HI2CStop
----
*Key line:* `HI2CStart` -- sends the start condition that every hardware I2C transmission must begin with, using the microcontroller's built-in I2C/TWI module.

**See Also:**

* <<_hi2csend,HI2CSend>> / <<_hi2creceive,HI2CReceive>> -- sending and receiving data after starting a transaction
* <<_hi2cstop,HI2CStop>> -- ending a transaction started with HI2CStart
* <<_hi2crestart,HI2CRestart>> -- repeating the start condition without stopping first
* <<_hi2cmode,HI2CMode>> -- selecting master or slave mode before starting

Supported in <HI2C.H>
