==== HserPrintCRLF

(((Serial Communications,HserPrintCRLF)))


*Syntax:*
[source,gcbasic]
----
    HserPrintCRLF [optional BYTE] [, 1 | 2  | 3 | 4 ]
----

*Command Availability:*

Available on all microcontrollers with a USART or UART module. +

Microchip PIC supports USART1 and 2.+
Atmel AVR supports USART 1,2,3 and 4.

*Enabling Constants:*

To enable the use of the USART these are the enabling constants. &#160;&#160;These constants are required.&#160;&#160;You can change the `USART_BAUD_RATE` and to meet your needs.&#160;&#160;For addition USART ports use `#define USART**n**_BAUD_RATE 9600` where `**n**`` is the required port number.

[source,gcbasic]
----
    'USART settings for USART1
    #define USART_BAUD_RATE 9600
    #define USART_TX_BLOCKING
    #define USART_DELAY OFF
----

*Explanation:*

This command will send ASCII codes 13 and 10 only using the hardware
RS232 module. ASCII codes 13 and 10 equate to a carriage return and line
feed.

Optionally, you can add a parameter. The number will determine the
number of ASCII codes 13 and 10 set to the hardware RS232 module.

Also you can choose the comport with second optional parameter if it is not the default comport 1. If there is no first optional parameter then you must have atleast acomma before it  to indicate this is the second parameter.

*Examples:*
[source,gcbasic]
----
  'This Line will send 1  CR and LF
  HserPrintCRLF    ' Will send a CR & LF to the terminal

  'This Line will send 2  times (CR and LF)
  HserPrintCRLF 2    ' Will send 2 times (CR & LF) to the terminal
            'out of comport 1

  'This Line will send 1  CR and LF
  HserPrintCRLF 1,2    ' Will send a CR & LF out of          ' <<< the HserPrintCRLF instruction
            'comport 2 to the terminal

----
*Key line:* `HserPrintCRLF 1,2` -- the first parameter (1) sets how many CR/LF pairs to send, and the second parameter (2) selects USART port 2 instead of the default port 1.

**See Also:**

* <<_hserprintbytecrlf,HserPrintByteCRLF>> -- sending a data byte before the CR/LF
