==== I2CAckpoll

(((I2C Software,I2CAckpoll)))


*Syntax:*
[subs="specialcharacters,quotes"]
----
	I2CAckpoll ( _I2C_device_address_ )
----
*Command Availability:*

Available on all microcontrollers except 12 bit instruction Microchip PIC microcontrollers (10F,
12F5xx, 16F5xx chips)

*Explanation:*

Should only be used when I2C routines are operating in Master mode, this
command will look for a specific I2C device on the I2C bus.

This sets a global variable `I2CAckPollState` that can be inspected in
your calling routine.

*Example:*
[source,gcbasic]
----
	 ...
	' ACK polling removes the need to for the 24xxxxx device to have a 5ms write time
	I2CACKPOLL( eeprom_device )          ' <<< the I2CAckpoll instruction
	' You check the exit state, use I2CAckPollState to check the state of
	' the acknowledge from the target device
	 ...
----
*Key line:* `I2CACKPOLL( eeprom_device )` -- repeatedly addresses `eeprom_device` on the bus, letting the caller poll `I2CAckPollState` until the device acknowledges, instead of waiting a fixed delay for its write cycle to finish.

Supported in <I2C.H>

**See Also:**

* <<_i2c_overview,I2C Overview>> -- category overview
* <<_i2cackpollstate,I2CAckPollState>> -- related command in the same category
* <<_i2creceive,I2CReceive>> -- related command in the same category
