==== IntegerToString

(((String Manipulation,IntegerToString)))


*Syntax:*
[subs="specialcharacters,quotes"]
----
    _stringvar_ = IntegerToString(_Integer_variable_)     'supports Integer.
----
*Command Availability:*

Available on all microcontrollers.

*Explanation:*

The `IntegerToString` function converts a number into a string. `_number_` can be any Integer variable, or a fixed number constant between -32768 and 32767 inclusive. For Byte numbers use `ByteToString()`, for Word numbers use `WordToString()`, for Long numbers use `LongToString()`, and for Single numbers use `SingleToString()`.

The string variable `_stringvar_` contains the same number, represented as a string. The length of the string returned is 9 characters.

This function is especially useful if a number needs to be added to the end of a string, or if a custom data-sending routine only supports the output of string variables.
{empty} +
{empty} +
This function does not support conversion of hexadecimal number strings.
{empty} +
{empty} +
*Note:* When calling `IntegerToString()`, do not leave a space between the function name and the opening parenthesis -- doing so produces a compiler error that is not obvious to diagnose.

[source,gcbasic]
----
    ' use this -- no space between IntegerToString and the opening parenthesis
    IntegerToString(number_variable)

    ' do not use this -- note the space before the parenthesis
    IntegerToString (number_variable)
----

*Example 1:*
[source,gcbasic]
----
    'Set chip model
    #chip 16F1936

    'Set up hardware serial connection
    #define USART_BAUD_RATE 9600
    #define USART_TX_BLOCKING

    Dim SensorReading as Integer

    'Take an A/D reading
    SensorReading = ReadAD10(AN0)

    'Create a string variable
    Dim OutVar As String

    'Fill string with sensor reading
    OutVar = IntegerToString(SensorReading)          ' <<< the IntegerToString instruction

    'Send
    HSerPrint OutVar
    HSerPrintCRLF
----
*Key line:* `OutVar = IntegerToString(SensorReading)` -- converts the signed integer ADC reading into a decimal string, ready to be transmitted over the serial connection with `HSerPrint`.

*Example 2:*
[source,gcbasic]
----
    '''************************************************************************
    '''  PIC: 16F18855
    '''  Compiler: GCB
    '''  IDE: GCode
    '''  Board: Xpress Evaluation Board
    '''  Date: June 2021

    ' ----- Configuration
      'Chip Settings.
      #chip 16f18855,32
      #Config CLRE_ON
      #option Explicit

    ; ----- Define Hardware settings

      'Set the PPS of the RS232 ports.
      UNLOCKPPS
        RC0PPS = 0x0010     'RC0->EUSART:TX;
        RXPPS  = 0x0011     'RC1->EUSART:RX;
      LOCKPPS

    ; ----- Constants
      #define USART_BAUD_RATE 19200
      #define USART_TX_BLOCKING

    ; ----- Variables
    dim Integervar as Integer

    ; ----- Main body of program commences here.
    Integervar = -10

    do
       wait 100 ms

       HSerPrint IntegerToString( Integervar )          ' <<< the IntegerToString instruction
       HSerPrintCRLF
       wait 1 s
    loop
    end
----
*Key line:* `HSerPrint IntegerToString( Integervar )` -- converts the negative Integer value -10 to a string and prints it directly, without needing an intermediate string variable.

**See Also:**

* <<_bytetostring,ByteToString>>
* <<_wordtostring,WordToString>>
* <<_longtostring,LongToString>>
* <<_singletostring,SingleToString>>
