//190217 Edited backlight reference and link
===== LCD_IO 2_74xx164

(((Liquid Crystal Display,LCD_IO_2_74xx164)))


*Using connection mode 2_74XX164:*

Use a Data and a Clock line. This manner is used when the LCD is
connected through a  shift register IC either using a 74HC164 or a 74LS164,
as detailed at https://gcbasic.sourceforge.net/library/DIAGRAMS/2-Wire%20LCD/[here].
This connection method is also called a 2-wire connection.

This is the preferred two wire method to connect via a shift register to an LCD display.

*Relevant Constants:*

Specific constants are used to control settings for the Liquid Crystal Display routines included with GCBASIC.  To set these constants the main program should specific constants to support the connection mode using #define.

When using connection mode 2_74XX164 only three constants must be set - all others are optional or can be ignored.

[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Default Value*

|`LCD_IO`
|The I/O mode.
|`2`

|`LCD_DB`
|The data pin used in 2-bit mode.
|*Mandated*

|`LCD_CB`
|The clock pin used in 2- bit mode.
|*Mandated*
|===


LCD.h supports in connection mode 2_74XX164 via the control of pin 11 of the 74HC164 / 74LS164 the background led/backlight.

How to connect and control the LCD background led: see <<_lcdbacklight,LCDBacklight>>.

*Example:*

[source,gcbasic]
----
include::lcd_io2_74xx164_code1.gcb[]
----
*Key line:* `Print "  Hello World."` -- writes to the second LCD line after `Locate 1,0`; both `Print` calls are shifted out over `LCD_DB`/`LCD_CB` to the 74HC164/74LS164, which the LCD itself decodes back into an 8-bit parallel write.

See further code examples at https://github.com/Anobium/Great-Cow-BASIC-Demonstration-Sources/tree/master/LCD_Solutions[Two Wire LCD Solutions].

See the separate sections of the Help file for the specifics of each Connection Mode.

**See Also:**

* <<_lcd_io_0,LCD_IO 0>> -- single subroutine, software-driven mode
* <<_lcd_io_1,LCD_IO 1>> -- 1-wire, via a 74HC595 shift register
* <<_lcd_io_2,LCD_IO 2>> -- 2-wire shift register, deprecated
* <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>> -- 2-wire via 74LS174, deprecated
* <<_lcd_io_3,LCD_IO 3>> -- 3-wire shift register with an added Enable line
* <<_lcd_io_4,LCD_IO 4>> -- 4-bit parallel connection
* <<_lcd_io_8,LCD_IO 8>> -- 8-bit parallel connection
* <<_lcd_io_10,LCD_IO 10>> -- I2C via a PCF8574/PCF8574A I/O expander
* <<_lcd_io_12,LCD_IO 12>> -- I2C via a Ywmjkdz-layout adapter
* <<_lcd_io_14,LCD_IO 14>> -- SPI expander
* <<_lcd_io_16,LCD_IO 16>> -- PIC16LF72 SPI expander
* <<_lcd_io_107,LCD_IO 107>> -- K107 serial adapter
