===== LCD_IO 2

(((Liquid Crystal Display,lcd_io2)))


*Using connection mode 2:*

This method uses a Data and a Clock line via a shift register to control the LCD display.
This method is used when the LCD is connected through a shift register IC either using a 74HC164 or a 74LS174, as detailed at https://gcbasic.sourceforge.net/library/DIAGRAMS/2-Wire%20LCD/[here].
This connection method is also called a 2-wire connection.


This is a *deprecated* method mode to connect an LCD display to a microcontroller via a shift registry either a 74LS174 (or a 74LS164 with diode connected to pin 11).   This method does not support backlight control and has no additional input/output pin.

If you have used the 2-wire mode prior to August 2015, please choose this method for your existing code.

See <<_lcd_io_2_74xx164,LCD_IO 2 74xx164>> for the preferred method to connect an LCD display to a microcomputer via a shift register.

*Relevant Constants:*

Specific constants are used to control settings for the Liquid Crystal Display routines included with GCBASIC. To set these constants the main program should specific constants to support the connection mode using #define.
When using 2-bit mode only three constants must be set - all others are optional or can be ignored.


[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Default Value*

|`LCD_IO`
|The I/O mode.
|`2`

|`LCD_DB`
|The data pin used in 2-bit mode.
|*Mandated*

|`LCD_CB`
|The clock pin used in 2- bit mode.
|*Mandated*
|===

*Example:*

[source,gcbasic]
----
include::lcd_io2_code1.gcb[]
----
*Key line:* `Print "  Hello World."` -- writes to the second LCD line after `Locate 1,0`; both `Print` calls are shifted out over `LCD_DB`/`LCD_CB` to the 74LS174, which the LCD itself decodes back into an 8-bit parallel write.

See further code examples at https://github.com/Anobium/Great-Cow-BASIC-Demonstration-Sources/tree/master/LCD_Solutions[Two Wire LCD Solutions].



See the separate sections of the Help file for the specifics of each
Connection Mode.

**See Also:**

* <<_lcd_io_0,LCD_IO 0>> -- single subroutine, software-driven mode
* <<_lcd_io_1,LCD_IO 1>> -- 1-wire, via a 74HC595 shift register
* <<_lcd_io_2_74xx164,LCD_IO 2_74xx164>> -- 2-wire via 74HC164/74LS164, the preferred 2-wire method
* <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>> -- 2-wire via 74LS174, deprecated
* <<_lcd_io_3,LCD_IO 3>> -- 3-wire shift register with an added Enable line
* <<_lcd_io_4,LCD_IO 4>> -- 4-bit parallel connection
* <<_lcd_io_8,LCD_IO 8>> -- 8-bit parallel connection
* <<_lcd_io_10,LCD_IO 10>> -- I2C via a PCF8574/PCF8574A I/O expander
* <<_lcd_io_12,LCD_IO 12>> -- I2C via a Ywmjkdz-layout adapter
* <<_lcd_io_14,LCD_IO 14>> -- SPI expander
* <<_lcd_io_16,LCD_IO 16>> -- PIC16LF72 SPI expander
* <<_lcd_io_107,LCD_IO 107>> -- K107 serial adapter
