===== LCD_IO 0

(((Liquid Crystal Display,lcd_i00)))


*Using connection mode 0:*

To use connection mode 0, a subroutine to write a byte to the LCD *must* be provided.

Optionally, another subroutine to read a byte from the LCD can also be
defined.  If the LCD was to be read, the function `LCDReadByte` would be set to the name of a function that reads the LCD and returns the data byte from the LCD.
If there is no way (or no requirement) to read from the LCD, then the `LCD_NO_RW` constant must be set.

In connection mode 0, the `LCD_RS` constant will be set automatically to an unused bit variable.
The higher level LCD commands (such as `Print` and `Locate`) will set it, and the subroutine is responsible for writing to the LCD.
The subroutine should handle the process and then set the RS pin on the LCD appropriately.

*Relevant Constants:*

Specific constants are used to control settings for the Liquid Crystal Display routines included with GCBASIC.  To set these constants the main program should specific constants to support the connection mode using #define.

When using connection mode 0 only one constant must be set - all others are optional or can be ignored.

[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Value*

|`LCD_IO`
|The I/O mode.
|`0`

|===

*Example:*

[source,gcbasic]
----
include::lcd_io0_code1.gcb[]
----
*Key line:* `print "Hello World."` -- exercises the connection exactly like any other LCD_IO mode; `LCDWriteByte` transparently calls `MySendToLCD` for every byte `print` sends, so higher-level commands need no special handling for connection mode 0.

See the separate sections of the Help file for the specifics of each
Connection Mode.

**See Also:**

* <<_lcd_io_1,LCD_IO 1>> -- 1-wire, via a 74HC595 shift register
* <<_lcd_io_2,LCD_IO 2>> -- 2-wire shift register, deprecated
* <<_lcd_io_2_74xx164,LCD_IO 2_74xx164>> -- 2-wire via 74HC164/74LS164, the preferred 2-wire method
* <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>> -- 2-wire via 74LS174, deprecated
* <<_lcd_io_3,LCD_IO 3>> -- 3-wire shift register with an added Enable line
* <<_lcd_io_4,LCD_IO 4>> -- 4-bit parallel connection
* <<_lcd_io_8,LCD_IO 8>> -- 8-bit parallel connection
* <<_lcd_io_10,LCD_IO 10>> -- I2C via a PCF8574/PCF8574A I/O expander
* <<_lcd_io_12,LCD_IO 12>> -- I2C via a Ywmjkdz-layout adapter
* <<_lcd_io_14,LCD_IO 14>> -- SPI expander
* <<_lcd_io_16,LCD_IO 16>> -- PIC16LF72 SPI expander
* <<_lcd_io_107,LCD_IO 107>> -- K107 serial adapter
