===== LCD_IO 2_74xx174

(((Liquid Crystal Display,LCD_IO_2_74xx174)))


LCD_IO 2_74xx174 has been deprecated as preferred method mode to connect an
LCD display to a microcontroller via a shift register either a 74LS174 (or a 74LS164 with
diode connected to pin 11). This method does not support backlight control and has no additional input/output pin.




See <<_lcd_io_2_74xx164,LCD_IO 2_74xx164>>  for the preferred method to connect
an LCD display to a microcontroller via a shift register.

**See Also:**

* <<_lcd_io_0,LCD_IO 0>> -- single subroutine, software-driven mode
* <<_lcd_io_1,LCD_IO 1>> -- 1-wire, via a 74HC595 shift register
* <<_lcd_io_2,LCD_IO 2>> -- 2-wire shift register, deprecated
* <<_lcd_io_2_74xx164,LCD_IO 2_74xx164>> -- 2-wire via 74HC164/74LS164, the preferred 2-wire method
* <<_lcd_io_3,LCD_IO 3>> -- 3-wire shift register with an added Enable line
* <<_lcd_io_4,LCD_IO 4>> -- 4-bit parallel connection
* <<_lcd_io_8,LCD_IO 8>> -- 8-bit parallel connection
* <<_lcd_io_10,LCD_IO 10>> -- I2C via a PCF8574/PCF8574A I/O expander
* <<_lcd_io_12,LCD_IO 12>> -- I2C via a Ywmjkdz-layout adapter
* <<_lcd_io_14,LCD_IO 14>> -- SPI expander
* <<_lcd_io_16,LCD_IO 16>> -- PIC16LF72 SPI expander
* <<_lcd_io_107,LCD_IO 107>> -- K107 serial adapter
