===== LCD_IO 107

(((Liquid Crystal Display,lcd_io107)))


*Using connection mode 107:*

The LCD is controlled via the serial port.
A type 107 is a K107 serial adapter.
To use mode 107 you must define the serial port as normal in your GCB code.
Then, serial speed to match the K107 adapter.


*Relevant Constants:*

These constants are used to control settings for the Liquid Crystal
Display routines included with GCBASIC. To set them, place a line in the
main program file that uses `#define` to assign a value to the particular
constant.

When using 107 mode only one constants must be set - all others can
be ignored.
[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Value*

|`LCD_IO`
|I/O mode
|`107` or `K107`

|===

*Example Code:*

[source,gcbasic]
----

    #chip 16f18313
    #option Explicit

    'Generated by PIC PPS Tool for GCBASIC
    'Generated for 16f18313
    '
    #startup InitPPS, 85
    #define PPSToolPart 16f18313

    Sub InitPPS

            'Module: EUSART
            RA5PPS = 0x0014    'TX > RA5

    End Sub
    'Template comment at the end of the config file

    'USART settings for USART1
    #define USART_BAUD_RATE 115200
    #define USART_TX_BLOCKING
    #define USART_DELAY OFF

    #define LCD_IO 107   'K107


    do Forever
      CLS
      Print "GCBASIC 2021"
      Locate 1, 0
      Print "Reading ADC ANA0"

      Locate 3, 0
      Print "Scaled = "
      Print Scale( ReadAD( ANA0 ), 0, 236, 0, 100 )
      wait 100 ms
    loop

----


See the separate sections of the Help file for the specifics of each
Connection Mode.

**See Also:**

* <<_lcd_io_0,LCD_IO 0>> -- single subroutine, software-driven mode
* <<_lcd_io_1,LCD_IO 1>> -- 1-wire, via a 74HC595 shift register
* <<_lcd_io_2,LCD_IO 2>> -- 2-wire shift register, deprecated
* <<_lcd_io_2_74xx164,LCD_IO 2_74xx164>> -- 2-wire via 74HC164/74LS164, the preferred 2-wire method
* <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>> -- 2-wire via 74LS174, deprecated
* <<_lcd_io_3,LCD_IO 3>> -- 3-wire shift register with an added Enable line
* <<_lcd_io_4,LCD_IO 4>> -- 4-bit parallel connection
* <<_lcd_io_8,LCD_IO 8>> -- 8-bit parallel connection
* <<_lcd_io_10,LCD_IO 10>> -- I2C via a PCF8574/PCF8574A I/O expander
* <<_lcd_io_12,LCD_IO 12>> -- I2C via a Ywmjkdz-layout adapter
* <<_lcd_io_14,LCD_IO 14>> -- SPI expander
* <<_lcd_io_16,LCD_IO 16>> -- PIC16LF72 SPI expander
