=== Overview - Linux Operating System

*Introduction:*
GCBASIC can be used when using the Linux Operating System.

This instructions are not distribution specific, but are for Linux only (not Windows).

*Instructions:*
Complete the following steps to compile and install GCBASIC for Linux:
[start=1]
 . Install FreeBasic from your distributions repository or http://www.freebasic.net/wiki/CompilerInstalling


 . Download the "GCBASIC - Linux Distribution" from SourceForge at https://sourceforge.net/projects/gcbasic/files/


 . Unrar/unpack GCB@Syn.rar to a location of your choice within your home directory (eg. within Downloads) with either a file manager or from a console.


 . From a console, change to the GCBASIC Sources in the unpacked directory:
----
   eg. cd ~/Downloads/GCB@Syn/GCBASIC/Sources/GCBASIC
----
[start=5]
 . Make sure that `install.sh` is set as executable (ie. `chmod +x install.sh`), and then execute: ./install.sh build


 . You will need root privileges for this step. You can switch user (su) to root, or optionally use `sudo`.
----
   Execute: [sudo] ./install.sh install
----
[start=7]
 . If you su'd to root, use `exit` to drop back to your normal user. Then, be sure to follow the instructions given by the script for updating your path.


 . Confirm proper execution, and the version, of GCBASIC by executing: gcbasic /version


Now you can create and compile GCBASIC source files.

*Programming microcontrollers:*

To program your microcontroller with your GCBASIC created hex file, you will need additional programming and programmer software.

For Microchip PIC microcontroller programming, you might find what you need at: www.pickitplus.co.uk  The PICKitPlus Team provide programmers and Linux software.

For Atmel AVR microcontroller programming, you will need `avrdude`. It should be available in your distributions repository. If not, check here: http://www.nongnu.org/avrdude/

{empty} +
{empty} +
{empty} +
{empty} +

=== Overview - Make ASM, Make HEX and Programming Operations using the provider Linux scripts

The scripts provided are intented assist in the creation of the ASM file ( from a GCBASIC source file ), creation of the HEX file ( also from a GCBASIC source file ) and to support programming operations ( often called `FLASH`ing the microcontroller ).

[cols=3, options="header,autowidth",width="80%"]
|===
|*Script*
|*Usage*
|*Example*

|`makeasm.sh`
|To compile the GCBASIC source program to create the ASM.
|`makeasm.sh sourcefile.gcb`


|`makehex.sh``
|To compile and asseble the GCBASIC source program to create the ASM and a microcontroller specific HEX file.
|`makehex.sh sourcefile.gcb`


|flash.sh
|To compile,asseble the GCBASIC source program to create the ASM and a microcontroller specific HEX file, and, then to program the microcontroller
|`flash.sh sourcefile.gcb`

|===

*Examples*

There are multiple constructs to run multiple programs on a single command line.&#160;&#160;The most common are ';' and '&&'

To run another command immadiately after running makehex.sh.&#160;&#160;Use the following: 
----
   makehex.sh sourcefile.gcb; anothercommand
----

To run another command only if makehex.sh does not exit with an error such as a compiler error.&#160;&#160;Use the following: 

----
   makehex.sh sourcefile.gcb && anothercommand
----

