=== PCF8574


The PCF8574 library supports the 8-bit quasi-bidirectional port on the PCG8574 via an I2C-bus interface.

The PCF8574 has a low current consumption and includes latched outputs with high current drive capability for directly driving LEDs.

It also possesses an interrupt line (INT) which can be connected to the interrupt logic of the microcontroller. By sending an interrupt signal on this line to the microcontroller, the remote I/O can inform the microcontroller if there is incoming data on its ports without having to communicate via the I2C-bus.

This means that the PCF8574 can remain a simple slave device.

The driver support two commands via I2C - this supports hardware and software I2C
PCF8574_sendbyte( PCF8574_device, [out_byte] ) where PCF8574_device is the 8bit I2C address and out_byte is the byte variable data to be sent
PCF8574_readbyte( PCF8574_device, [in_byte] ) where PCF8574_device is the 8bit I2C address and in_byte is the byte variable data to be received

To address a specific slave. Use the constant #DEFINE PCF8574_DEVICE_1 0X4E where 0x4E is the correct address identified by I2C Discovery.

I2C must be defined prior to calling the methods shown above. Either Software or Hardware I2C is supported.


*Example*

----

// Include this specific library.  This is mandated
 #INCLUDE <PCF8574.H>

    //! send a variable to the I2C device that sets the device ports
    PCF8574_sendbyte(PCF8574_DEVICE_1, LEDStatus )

    //! read the status of the port into the variable Portstatus
    PCF8574_readbyte(PCF8574_DEVICE_1, PortStatus )


----
