// Edit EvanV 171016 0,95.010.RC9+
==== PWMOn

(((Pulse width modulation,PWMOn)))


*Syntax:*
[source,gcbasic]
----

    PWMOn

----

*Command Availability:*

Only available on Microchip PIC microcontrollers with Capture/Compare/PWM
module CCP1.

This command does not operate on any other CCP channel.

*Explanation:*

*Example 1:*

This command will enable the output of the CCP1/PWM module on the Microchip PIC microcontroller.

[source,gcbasic]
----
    'This program will enable a 76 Khz PWM signal, with a duty cycle
    'of 80%. It will emit the signal for 10 seconds, then stop.
    #define PWM_Freq 76    'Set frequency in KHz
    #define PWM_Duty 80    'Set duty cycle to 80 %
    PWMOn                  'Turn on the PWM          ' <<< the PWMOn instruction
    WAIT 10 s              'Wait 10 seconds
    PWMOff                 'Turn off the PWM
----
*Key line:* `PWMOn` -- enables the CCP1 module's output pin using the frequency and duty cycle already set by the `PWM_Freq` and `PWM_Duty` constants above; the signal keeps running until `PWMOff` is called.
{empty} +
{empty} +

*Example 2:*

This command will enable the output of the CCP1/PWM module on the Microchip PIC microcontroller.

Note the chip frequency.

[source,gcbasic]
----
    'This program will enable a 62Hz PWM signal, with a duty cycle
    'of 50%.


    #Chip 12F1840, 1

    dir porta.2 out
    #define PWM_Freq .0625    'Set frequency in Hz equates to 62Hz
    #define PWM_Duty 50       'Set duty cycle to 80 %
    PWMON

    Do
    loop

----
{empty} +
{empty} +
*Example 3:*

This command will enable the output of the CCP1/PWM module on the Microchip PIC microcontroller.

Note the chip frequency.

[source,gcbasic]
----
    'This program will enable a 7.7Hz PWM signal, with a duty cycle
    'of 50%.


    #Chip 12F1840, 0.125

    dir porta.2 out
    #define PWM_Freq .0077   'Set frequency in Hz equates to 7.7Hz
    #define PWM_Duty 50       'Set duty cycle to 50 %
    PWMON

    Do
    loop

----
{empty} +
{empty} +

**See Also:**

* <<_pwmoff,PWMOff>> -- the counterpart command that disables the CCP1 PWM output
