//erv 04110218
==== SAFReadWord

(((SAFM,SAFReadWord)))



*Syntax:*
[subs="specialcharacters,quotes"]
----
    'as a subroutine
    SAFReadWord ( location, data_word_variable )

    'as a function
    data_word_variable = SAFReadWord ( location )
----
*Command Availability:*

Available on all PIC microcontrollers with SAFM memory.

*Explanation:*
{empty} +
{empty} +
`SAFReadWord` is used to read information, word values, from SAFM so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` represents the location or relative address to read. The location ranges from 0 to `SAF_BYTES - 1`.&#160;&#160;&#160; 
Each data word requires 2 SAF locations, so the location ranges from either 0 to 254 or 0 to 126 (in steps of 2), depending on the device. 
{empty} +
{empty} +
`data` is the word data to be read from the SAFM location.&#160;&#160;&#160;
This must be a word variable.
{empty} +
{empty} +
This method reads word information from SAFM given the relative location in SAFM.&#160;&#160;&#160;
{empty} +
{empty} +
*Example 1:*
[source,gcbasic]
----
    '... code preamble to select part
    '... code to setup serial

    'The following example uses a subroutine to read an SAFM location into a word variable.

    dim data_word_variable as word
    
    ;Write a word to SAF location 64
    SAFWriteWord(  64, 0x1234 )
    
    ; Read the Word from SAF location 64
    SAFReadWord ( 64, data_word_variable  )          ' <<< the subroutine form of SAFReadWord this page documents
    
    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF
----
*Key line:* `SAFReadWord ( 64, data_word_variable )` -- reads the 16-bit value stored at SAFM location 64 into `data_word_variable`.

If example 1 were displayed on a serial terminal, the result would show:

[source,gcbasic]
----
    Value = 4660
----

*Example 2:*
[source,gcbasic]
----
    '... code preamble to select part
    '... code to setup serial

    'The following example uses a function to read an SAFM location into a word variable.

    dim data_word_variable as word
    
    ;Write a word to SAF location 64
    SAFWriteWord(  64, 0x4321 )
    
    ; Read the Word from SAF location 64
    data_word_variable = SAFReadWord ( 64 )          ' <<< the function form of SAFReadWord this page documents

    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF

----
*Key line:* `data_word_variable = SAFReadWord ( 64 )` -- the function form of the same read, returning the 16-bit value directly.

If example 2 were displayed on a serial terminal, the result would show:

[source,gcbasic]
----
    Value = 17185
----

**See Also:**

* <<_safm_overview,SAFM Overview>>
* <<_safread,SAFRead>>
* <<_safwrite,SAFWrite>>
* <<_safwriteword,SAFWriteWord>>
* <<_safreadblock,SAFReadBlock>>
* <<_safwriteblock,SAFWriteBlock>>
* <<_saferaseblock,SAFEraseBlock>>
