==== SAFM Overview

(((SAFM,SAFM Overview)))


*Introduction:*

Some Advanced (18F) and some Enhanced Mid-Range (16F) Microchip PIC devices support Storage Area Flash (SAF) memory. These devices also include EEPROM memory.&#160;&#160;&#160;
SAF memory is not high endurance, meaning it does not have an endurance of 100K write cycles.&#160;&#160;&#160;
SAF has the same endurance as regular flash memory, usually specified as 10K write cycles.&#160;&#160;&#160;
{empty} +
{empty} +
SAF memory appears at the top of program memory space and can be used for any purpose, like regular flash program memory.&#160;&#160;&#160; 
Storage Area Flash is intended to be used to store data, such as device calibration data, RF device register settings, and other data. SAFM can be read as frequently as necessary.&#160;&#160;&#160; However, it is not intended to be written frequently like EEPROM. If non-volatile memory needs to be written frequently, it is best to use the EEPROM on these devices.     
{empty} +
{empty} +
As with all flash memory, data must be erased before it can be written, and writing this memory will stall the device for a few ms. &#160;&#160;&#160;
Methods to read, write, and erase the SAF memory are included in GCBASIC and are described in this introduction.
{empty} +
{empty} +
The `hefsaf.h` library supports SAF operations for GCBASIC.
{empty} +
{empty} +
Note: By default, GCBASIC will use SAF memory for regular executable code unless it is told otherwise.&#160;&#160;&#160;
If you wish to store data here, you should reserve the SAF memory by using the compiler option, as shown below, to reserve 128 words of SAF memory:&#160;&#160;&#160;This equates to 256 bytes on PIC 18F microcontrollers and 128 bytes on PIC 16F microcontrollers.
[source,gcbasic]
----
    #option ReserveHighProg 128
----
SAF memory is a block of memory locations found at the top of the flash program memory.&#160;&#160;&#160;
Each memory location can be used to hold a variable value, either a byte or a word depending on the specific device.&#160;&#160;&#160;
The main difference between SAF memory and EEPROM is that EEPROM allows byte-by-byte erase, whereas SAF memory does not.&#160;&#160;&#160;
With SAF memory, data must be erased before a write, and the erase can only be performed in blocks of memory.&#160;&#160;&#160;
The blocks, also called rows, are a fixed size associated with the specific device.&#160;&#160;&#160;
{empty} +
{empty} +
GCBASIC handles the erase operation automatically.&#160;&#160;&#160;
When a write operation is used, the GCBASIC library reads to a buffer, updates the buffer, erases the block, and finally writes the buffer back to SAFM.&#160;&#160;&#160;
The complexity of using SAF memory is reduced by the automatic handling of these operations.&#160;&#160;&#160;
{empty} +
{empty} +
The library provides a set of methods to support use of SAF memory.
{empty} +
{empty} +
[cols="2,1,3",width="80%"]
|===
|Method
|Parameters
|Usage

|`SAFWrite`
|a subroutine with the parameters: location, byte value
|SAFWrite ( location, byte_variable )

|`SAFWriteWord`
|a subroutine with the parameters: location, word_value
|SAFWriteWord ( location, word_variable  )

|`SAFRead`
|a function with the parameters: location returns a byte value
|byte_variable = SAFRead ( location  )

|`SAFRead`
|a subroutine with the parameters: location, byte_value
|SAFRead ( location , out_byte_variable )

|`SAFReadWord`
|a function with the parameters: location returns a word value
|word_variable = SAFRead ( location  )

|`SAFReadWord`
|a subroutine with the parameters: location, word_value
|SAFRead ( location , word_variable )

|`SAFEraseBlock`
|a subroutine with the parameters: block_number
|SAFEraseBlock ( 0 )
{empty} +
{empty} +
A value of 0, 1, 2, 3, etc.

|`SAFWriteBlock`
|a subroutine with the parameters: block_number, buffer() [,num_blocks ]
|SAFWriteBlock( 0, myMemoryBuffer ) 'where myMemoryBuffer is an Array or a String
{empty} +
{empty} +
The array or string contains the values to be written to the SAFM.

|`SAFReadBlock`
|a subroutine with the parameters: block_number, buffer() [, num_blocks ]
|SAFReadBlock( 0, myMemoryBuffer ) 'where myMemoryBuffer is an Array or a String.
{empty} +
{empty} +
The array or string contains the values read from the SAFM.

|===


{empty} +
{empty} +
The library also defines a set of constants that are specific to the device.&#160;&#160;&#160;
These may be useful in the user program.&#160;&#160;&#160;
These constants are used by the library.&#160;&#160;&#160;
A user may use these public constants.
{empty} +
{empty} +
[cols="2,1,3",width="80%"]
|===
|Constant
|Type
|Usage

|`SAF_ROWSIZE_BYTES`
|Byte
|Size of an SAFM block in bytes

|`SAF_WORDS` and `SAF_BYTES`
|Word or a Byte
|ChipSAFMemWords parameter from the device .dat file

|`SAF_START_ADDR`
|Word
|Starting address of SAFM

|`SAF_NUM_BLOCKS`
|Byte
|Number of blocks of SAFM

|`CHIPWORDS`
|Word
|Device specific constant for the total flash size

|`CHIPSAFMEMWORDS`
|Word
|Device specific constant for the number of SAFM words available

|`CHIPERASEROWSIZEWORDS`
|Word
|Device specific constant for the number of SAFM in an erase row

|===
{empty} +
*Warning*
{empty} +
{empty} +
Whenever you update the hex file of your Microchip PIC microcontroller with your programmer, you MAY erase the data stored in SAF memory.&#160;&#160;&#160;
If you want to avoid that, you will have to flash your Microchip PIC microcontroller with software that allows memory exclusion when flashing.&#160;&#160;&#160;
This is the case with Microchip PIC MPLAB IPE (go to `Advanced Mode/Enter password/Select Memory/Tick "Preserve Flash on Program"/
Enter Start and End address` of your SAFM).&#160;&#160;&#160;Or, simply use the PICkitPlus suite of software to preserve SAF memory during programming.

**See Also:**

* <<_safread,SAFRead>>
* <<_safreadword,SAFReadWord>>
* <<_safwrite,SAFWrite>>
* <<_safwriteword,SAFWriteWord>>
* <<_safreadblock,SAFReadBlock>>
* <<_safwriteblock,SAFWriteBlock>>
* <<_saferaseblock,SAFEraseBlock>>
* <<_hefm_overview,HEFM Overview>> -- the equivalent high-endurance flash memory feature on other PIC families
