==== SAFWriteBlock

(((SAFM,SAFWriteBlock)))



*Syntax:*
[subs="specialcharacters,quotes"]
----
    SAFWriteBlock ( block_number,  buffer(), [, num_bytes] )
----
*Command Availability:*

Available on all PIC microcontrollers with SAFM memory.

*Explanation:*
{empty} +
{empty} +
`SAFWriteBlock` is used to write information from a user buffer to SAFM.&#160;&#160;&#160;
Once the block is written, it can be accessed for use within a user program.
{empty} +
{empty} +
The parameters are as follows:
{empty} +
{empty} +
`block_number` represents the block to be written to.&#160;&#160;&#160;
The block_number parameter is used to calculate the physical memory location(s) that are updated.
{empty} +
{empty} +
`buffer()` represents an array or string.&#160;&#160;&#160;
The buffer is used as the data source that is written to the SAFM block.&#160;&#160;&#160;
The buffer is handled as a buffer of byte values.&#160;&#160;&#160;
In most cases the buffer should be the same size as a row/block of SAFM.&#160;&#160;&#160;
For most PIC microcontrollers this will be 32 bytes.&#160;&#160;&#160;
Best practice is to size the buffer using the `SAF_ROWSIZE_BYTES` constant.&#160;&#160;&#160;
If the size of the buffer exceeds the device-specific `SAF_ROWSIZE_BYTES`, the excess data will not be handled, and the buffer will be truncated at the `SAF_ROWSIZE_BYTES` limit.&#160;&#160;&#160;
{empty} +
{empty} +
`num_bytes` is an optional parameter, and can be used to specify the number of bytes to write to SAFM, starting at the first location in the selected SAFM block.&#160;&#160;&#160;
This parameter is not normally required, as the default is set to the GCBASIC constant `SAF_ROWSIZE_BYTES`.
{empty} +
{empty} +
*Example 1:*
[source,gcbasic]
----
    #chip 18F24K42, 16
    '... code preamble to setup PPS
    '... code to setup serial

      Dim My_Buffer(SAF_ROWSIZE_BYTES)
      Dim index as byte

      ;Write some data to Block 2
      My_Buffer = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32
      SAFWriteBlock(2, My_Buffer())          ' <<< the SAFWriteBlock instruction

      ;Read the data back from SAFM using SAFReadBlock
      SAFReadBlock( 2 , My_buffer() )

     ;Send the data to a terminal in decimal format
      index = 1
      Repeat SAF_ROWSIZE_BYTES
          Hserprint(My_Buffer(index))
          HserPrint " "
          index++
     End Repeat
----
*Key line:* `SAFWriteBlock(2, My_Buffer())` -- writes the full 32-byte `My_Buffer()` array into block 2 of SAFM in one call, rather than one `SAFWrite` per byte.

**See Also:**

* <<_safm_overview,SAFM Overview>>
* <<_safread,SAFRead>>
* <<_safreadword,SAFReadWord>>
* <<_safwrite,SAFWrite>>
* <<_safwriteword,SAFWriteWord>>
* <<_safreadblock,SAFReadBlock>>
* <<_saferaseblock,SAFEraseBlock>>
