==== ST7920 Controllers

This section covers GLCD devices that use the ST7920 graphics controller.


The Great Cow BASIC constants for control of the connectivity are shown
in the table below. The only connectivity option the 8-bit mode where 8
pins are connected between the microcontroller and the GLCD to control the
data bus. +

The ST7920 GLCD is graphics and character mixed mode display. +

ST7920 LCD controller/driver IC can display alphabets, numbers, Chinese
fonts and self-defined characters.&#160;&#160;&#160;It supports 3 kinds of bus interface,
namely 8-bit, 4-bit and serial.&#160;&#160;&#160;Great Cow BASIC is currently supports
8-bit only. For LCD only operations (text characters only) you can use
the Great Cow BASIC LCD routines. +

All functions, including display RAM, Character Generation ROM, LCD
display drivers and control circuits are all in a one-chip solution.
With a minimum system configuration, a Chinese character display system
can be easily achieved. +

The ST7920 includes character ROM with 8192 16x16 dots Chinese fonts and
126 16x8 dots half-width alphanumerical fonts.&#160;&#160;&#160;It supports 64x256 dots
graphic display area for graphic display (GDRAM).&#160;&#160;&#160;Mix-mode display with
both character and graphic data is possible.&#160;&#160;&#160;ST7920 has built-in CGRAM
and provide 4 sets software programmable 16x16 fonts. +


To use the ST7920 driver simply include the following in your user code.  This will initialise the driver. +

----
    #include <glcd.h>
    #DEFINE GLCD_TYPE GLCD_TYPE_ST7920

    #define GLCD_Enable     PORTA.1           'example port setting
    #define GLCD_RS         PORTa.0           'example port setting
    #define GLCD_RW         PORTA.2           'example port setting
    #define GLCD_RESET      PORTA.3           'example port setting
    #define GLCD_DATA_PORT  PORTD             'example port setting


----


The Great Cow BASIC constants for the interface to the controller are shown in the table below.



[cols=3, options="header,autowidth"]
|===
|*Constants*
|*Controls*
|*Options*

|`GLCD_TYPE`
|`GLCD_TYPE_ST7920`
|Required

|`GLCD_DATA_PORT`
|Specifies the output port that is connected between the microcontroller
and the GLCD.
|Required

|`GLCD_RS`
|Specifies the output pin that is connected to Register Select on the
GLCD.
|Required

|`GLCD_RW`
|Specifies the output pin that is connected to Read/Write on the GLCD.
The R/W pin can be disabled*.
|*_Must be defined_* _unless R/W is disabled), see_ `GLCD_NO_RW`

|`GLCD_RESET`
|Specifies the output pin that is connected to Reset on the GLCD.
|Required

|`GLCD_ENABLE`
|Specifies the output pin that is connected to Enable on the GLCD.
|Required


|`GLCD_NO_RW`
|Disables read/write inspection of the device during read/write
operations
|Optional, but recommend NOT to set.
The R/W pin can be disabled by setting the `GLCD_NO_RW` constant. If this
is done, there is no need for the `R/W` to be connected to the chip, and
no need for the `LCD_RW` constant to be set. Ensure that the `R/W` line on
the LCD is connected to ground if not used.

3+| Constants that control the timing of the library



|`ST7920READDELAY`
|Set the time delay between read data transmissions.
|Optional, set to `20` us as the default value.

|`ST7920WRITEDELAY`
|Set the time delay between write data transmissions.
|Optional, set to `2` us as the default value.


    ' read delay of 25 is required at 32mhz, this can be reduced to 0 for slower clock speeds
    #DEFINE ST7920READDELAY 25
    ' write delay of 2 is required at 32mhz.  this can be reduced to 1 for slower clock speeds
    #DEFINE ST7920WRITEDELAY 2

|===




The Great Cow BASIC constants for control display characteristics are shown in the table below.  +

[cols="1,1,1", options="header,autowidth"]
|===
|*Constants*
|*Controls*
|*Default*

|`GLCD_WIDTH`
|The width parameter of the GLCD
|`128`&#160;&#160;cannot be changed.

|`GLCD_HEIGHT`
|The height parameter of the GLCD
|`64`&#160;&#160;cannot be changed.

|===

The Great Cow BASIC commands supported for this GLCD are shown in the
table below. For device specific see the commands with the prefix of
ST7920*.

[cols=3, options="header,autowidth"]
|===
|*Command*
|*Purpose*
|*Example*

|`GLCDCLS`
|Clear screen of GLCD
|`GLCDCLS`

|`GLCDPrint`
|Print string of characters on GLCD using GCB font set
|`GLCDPrint( Xposition, Yposition, Stringvariable )`

|`GLCDDrawChar`
|Print character on GLCD using GCB font set
|`GLCDDrawChar( Xposition, Yposition, CharCode )`

|`GLCDDrawString`
|Print characters on GLCD using GCB font set
|`GLCDDrawString( Xposition, Yposition, Stringvariable )`

|`Box`
|Draw a box on the GLCD to a specific size
|`Box ( Xposition1, Yposition1, Xposition2, Yposition2, [Optional In
LineColour as 0 or 1] )`

|`FilledBox`
|Draw a box on the GLCD to a specific size that is filled with the
foreground colour.
|`FilledBox (Xposition1, Yposition1, Xposition2, Yposition2, [Optional In
LineColour 0 or 1] )`

|`Line`
|Draw a line on the GLCD to a specific length that is filled with the
specific attribute.
|`Line ( Xposition1, Yposition1, Xposition2, Yposition2, [Optional In
LineColour 0 or 1] )`

|`PSet`
|Set a pixel on the GLCD at a specific position that is set with the
specific attribute.
|`PSet(Xposition, Yposition, Pixel Colour 0 or 1)`

3+|

The following methods ( calls ) are available for expert use.
 +
 
|`GLCDWriteByte`
|Set a byte value to the controller, see the datasheet for usage.
|`GLCDWriteByte (LCDByte)`

|`GLCDReadByte`
|Read a byte value from the controller, see the datasheet for usage.
|`bytevariable = GLCDReadByte`
|===

For a TS7920 datasheet, please refer
http://www.crystalfontz.com/controllers/ST7920.pdf[here.]

This example shows how to drive a ST7920 based Graphic LCD module with
the built in commands of Great Cow BASIC. See
http://www.greatcowbasic.com/sample-projects.html[Graphic LCD] for
details, this is an external web site.

*Example 1:*
----
include::codesegment0001.gcb[]    
----

*Example 2:*

----
include::codesegment0002.gcb[]
----




*For more help, see*
<<_glcdcls,GLCDCLS>>, <<_glcddrawchar,GLCDDrawChar>>, <<_glcdprint,GLCDPrint>>, <<_glcdreadbyte,GLCDReadByte>>, <<_glcdwritebyte,GLCDWriteByte>> or <<_pset,Pset>>

Supported in <GLCD.H>
